"""VectorBT scalping strategy configuration."""

# EMA Ribbon Scalp defaults
EMA_RIBBON_FAST_WINDOW = 8
EMA_RIBBON_MEDIUM_WINDOW = 13
EMA_RIBBON_SLOW_WINDOW = 21
EMA_RIBBON_PULLBACK_RECLAIM = True
EMA_RIBBON_ENTRY_COOLDOWN_BARS = 2

# BB/RSI Mean Reversion defaults
BB_RSI_WINDOW = 20
BB_RSI_STD = 2.0
BB_RSI_RSI_WINDOW = 7
BB_RSI_OVERSOLD = 30.0
BB_RSI_OVERBOUGHT = 70.0

# Shared risk and execution defaults
SCALP_ATR_WINDOW = 14
SCALP_ATR_MULTIPLE = 1.5
SCALP_RISK_FRACTION = 0.005
SCALP_TP_R_MULTIPLE = 2.0
SCALP_FEES = 0.0005
SCALP_SLIPPAGE = 0.0001

# Hyperparameter ranges
EMA_RIBBON_FAST_WINDOWS = [5, 8, 10]
EMA_RIBBON_MEDIUM_WINDOWS = [13, 16, 21]
EMA_RIBBON_SLOW_WINDOWS = [21, 34, 55]
EMA_RIBBON_ENTRY_COOLDOWN_BARS_VALUES = [0, 1, 2, 3, 5]

BB_RSI_WINDOWS = [14, 20, 26]
BB_RSI_STD_VALUES = [1.5, 2.0, 2.5]
BB_RSI_RSI_WINDOWS = [5, 7, 9]
BB_RSI_OVERSOLD_VALUES = [20.0, 25.0, 30.0]
BB_RSI_OVERBOUGHT_VALUES = [70.0, 75.0, 80.0]
